// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIiy2tjxu7etH-bY1PHLEUe-hDp61q2xQ',
    appId: '1:240343422145:web:ec8582b8c33a8a374ff040',
    messagingSenderId: '240343422145',
    projectId: 'plantifyecommerceapp',
    authDomain: 'plantifyecommerceapp.firebaseapp.com',
    storageBucket: 'plantifyecommerceapp.firebasestorage.app',
    measurementId: 'G-8F8S0EJFWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwl6essGBed4Lxk_YH_aq2T6MfMxXxLRk',
    appId: '1:240343422145:android:b3d5c990be78d8a74ff040',
    messagingSenderId: '240343422145',
    projectId: 'plantifyecommerceapp',
    storageBucket: 'plantifyecommerceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3clCifhPgbYXKB9SBULkcJItjfY8o_Zc',
    appId: '1:240343422145:ios:e5c77d451f972dcd4ff040',
    messagingSenderId: '240343422145',
    projectId: 'plantifyecommerceapp',
    storageBucket: 'plantifyecommerceapp.firebasestorage.app',
    androidClientId: '240343422145-oitj07jtmp3fpgfm411l6t5cgct4pnjk.apps.googleusercontent.com',
    iosClientId: '240343422145-n7fs18jnag4s21o9rnsvg93bbbarhv9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantifyecommerceshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3clCifhPgbYXKB9SBULkcJItjfY8o_Zc',
    appId: '1:240343422145:ios:e5c77d451f972dcd4ff040',
    messagingSenderId: '240343422145',
    projectId: 'plantifyecommerceapp',
    storageBucket: 'plantifyecommerceapp.firebasestorage.app',
    androidClientId: '240343422145-oitj07jtmp3fpgfm411l6t5cgct4pnjk.apps.googleusercontent.com',
    iosClientId: '240343422145-n7fs18jnag4s21o9rnsvg93bbbarhv9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantifyecommerceshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIiy2tjxu7etH-bY1PHLEUe-hDp61q2xQ',
    appId: '1:240343422145:web:f68a1e92a4cc9e484ff040',
    messagingSenderId: '240343422145',
    projectId: 'plantifyecommerceapp',
    authDomain: 'plantifyecommerceapp.firebaseapp.com',
    storageBucket: 'plantifyecommerceapp.firebasestorage.app',
    measurementId: 'G-T3TW3QTB5R',
  );

}